{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autogen-kernel.fullname" . }}
  labels:
    {{- include "autogen-kernel.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | toString | quote }}
  {{- end }}
{{- end }}
