# specs/07_gateway/orchestrator/CROSS_VERTICAL.py
"""
Cross-Vertical Orchestrator (The Composer).
Generates multi-project systems (Frontend + Backend + Infra) with shared contracts.
"""

from __future__ import annotations
import asyncio
import uuid
from dataclasses import dataclass, field
from typing: Dict, List, Any, Optional
from pathlib import Path

from kernel.graph.builder import build_graph
from kernel.vertical.loader import VerticalLoader
from kernel.protocols import GenerateRequest, VerticalManifest
from kernel.state import AgentState

@dataclass
class SubProjectSpec:
    vertical_id: str
    name: str
    prompt: str
    tech_stack_hints: Dict[str, str]
    contracts: Dict[str, Any] = field(default_factory=dict) # Injected shared contracts
    depends_on: List[str] = field(default_factory=list) # Other sub-project names

@dataclass
class CompositionPlan:
    project_name: str
    sub_projects: List[SubProjectSpec]
    shared_contracts: Dict[str, Any] # OpenAPI, Protobuf, SQL, Events
    integration_tests: List[str] = field(default_factory=list)

class CrossVerticalOrchestrator:
    def __init__(self, vertical_loader: VerticalLoader):
        self.loader = vertical_loader
        self.verticals: Dict[str, VerticalManifest] = {}

    async def initialize(self):
        self.verticals = await self.loader.discover()

    async def compose(self, request: GenerateRequest) -> CompositionPlan:
        """Meta-Planning: Decompose monolithic prompt into vertical-specific sub-projects."""
        # This uses a specialized "Architect" LLM (router/planner model)
        # For spec, we define the output structure.
        
        # Example Output for "SaaS with Billing Microservice":
        return CompositionPlan(
            project_name=request.tech_stack_hints.get("project_name", "composed-system"),
            shared_contracts={
                "api": { "openapi": "shared/openapi.yaml" }, # Generated by Composer
                "database": { "sql": "shared/schema.sql" },
                "events": { "schemas": "shared/events/" }
            },
            sub_projects=[
                SubProjectSpec(
                    vertical_id="saas_web",
                    name="frontend",
                    prompt="Generate the Next.js Frontend consuming the Billing API defined in shared contracts.",
                    tech_stack_hints={"api_contract": "shared/openapi.yaml"},
                    depends_on=["billing-api"]
                ),
                SubProjectSpec(
                    vertical_id="py_fastapi_microsvc",
                    name="billing-api",
                    prompt="Generate FastAPI Billing Service with Stripe, implementing the shared OpenAPI contract.",
                    tech_stack_hints={"openapi_spec": "shared/openapi.yaml"},
                    depends_on=[]
                ),
                SubProjectSpec(
                    vertical_id="iac_terraform",
                    name="infra",
                    prompt="Generate Terraform for AWS: ECS Fargate for API, Vercel/CloudFront for Frontend, RDS, ElastiCache.",
                    tech_stack_hints={},
                    depends_on=["billing-api", "frontend"]
                )
            ],
            integration_tests=["contract_test_openapi", "docker_compose_up_smoke"]
        )

    async def execute_plan(self, plan: CompositionPlan, base_request: GenerateRequest) -> Dict[str, Any]:
        """Execute sub-projects in topological order with contract injection."""
        # 1. Resolve Dependency Order
        from kernel.skills.registry import SkillRegistry # Reuse topo sort logic
        # Simplified: Assume plan.sub_projects is already ordered.
        
        results = {}
        shared_contracts = plan.shared_contracts.copy()
        
        for sub_spec in plan.sub_projects:
            # 1. Inject Contracts into Prompt/Context
            enriched_prompt = self._inject_contracts(sub_spec.prompt, shared_contracts)
            
            # 2. Create Sub-Request
            sub_request = GenerateRequest(
                prompt=enriched_prompt,
                vertical_id=sub_spec.vertical_id,
                tech_stack_hints={**base_request.tech_stack_hints, **sub_spec.tech_stack_hints},
                constraints=base_request.constraints + [f"Part of composition: {plan.project_name}"],
                context_files=base_request.context_files
            )
            
            # 3. Run Kernel (Async, potentially parallel if no deps)
            vertical = self.loader.load_vertical(sub_spec.vertical_id)
            graph = build_graph(vertical)
            
            run_id = f"{base_request.run_id}-{sub_spec.name}"
            config = {"configurable": {"thread_id": run_id, "vertical": vertical}}
            
            final_state = await graph.ainvoke(sub_request.model_dump(), config=config)
            
            if final_state.get("status") != "completed":
                raise RuntimeError(f"Sub-project {sub_spec.name} failed: {final_state.get('error')}")
            
            # 4. Extract Contracts from Result (e.g., generated OpenAPI from FastAPI)
            new_contracts = self._extract_contracts(final_state, sub_spec.vertical_id)
            shared_contracts.update(new_contracts)
            
            results[sub_spec.name] = {
                "run_id": run_id,
                "artifact_url": final_state["final_artifact"]["artifact_url"],
                "contracts": new_contracts
            }
            
            # Stream progress to parent run
            # await stream_log(base_request.run_id, "info", f"Completed sub-project: {sub_spec.name}")
        
        # 5. Generate Integration Glue (docker-compose, skaffold, root README)
        glue_artifact = await self._generate_integration_glue(plan, results)
        
        return {
            "sub_projects": results,
            "integration_glue": glue_artifact,
            "shared_contracts": shared_contracts
        }

    def _inject_contracts(self, prompt: str, contracts: Dict) -> str:
        if not contracts: return prompt
        contract_md = "## Shared Contracts (MANDATORY)\n"
        for name, content in contracts.items():
            contract_md += f"### {name}\n```yaml\n{content}\n```\n"
        return f"{prompt}\n\n---\n{contract_md}"

    def _extract_contracts(self, state: AgentState, vertical_id: str) -> Dict:
        """Extract generated contracts (OpenAPI, SQL, Protobuf) from artifact."""
        # Implementation: Read specific files from artifact (via sandbox download or state metadata)
        # e.g., state['metadata'].get('generated_openapi')
        return state.get("metadata", {}).get("generated_contracts", {})

    async def _generate_integration_glue(self, plan: CompositionPlan, results: Dict) -> Dict:
        """Generate docker-compose.yml, skaffold.yaml, root README, Makefile."""
        # This is a Skill itself: `generate_integration_glue`
        # For now, return placeholder structure.
        return {
            "docker_compose": "version: '3.8'\nservices:\n  # ... generated from results",
            "skaffold_yaml": "apiVersion: skaffold/v4\n# ...",
            "readme_md": f"# {plan.project_name}\n\nGenerated composition.\n",
            "makefile": "up:\n\tdocker-compose up -d\n"
        }
